language: go

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/modocache/gover
  - - go get github.com/mattn/goveralls

script:
  - go test -v ./pkg/toyrobot
  - $GOPATH/bin/goveralls -service=travis-ci

notifications:
  email: false
